#!/bin/sh

case "$2" in
    POST-INSTALL)
    if [ -f /etc/rc.conf ]; then
        echo 'slim_enable="YES"' >> /etc/rc.conf
    fi

    # copy xinitrc from freebsd dir to /usr/share/skel
    cp -af /usr/local/share/freebsd/slim/etc/skel/xinitrc /usr/share/skel/dot.xinitrc
    ;;
esac

exit 0

